### ISSUE TITLE
Can file and directory names have section numbers prepended for better sorting?

### ISSUE THREAD

**Issue by junkyardsparkle** [elstoc/dtdocs#75]
I haven't had a chance to look into Hugo etc yet, so I don't really know what all the practical considerations are concerning the large number of files containing small amounts of text, but... if this is going to be the case, is there any possibility of the files and directories being named in such a way that they sort alphanumerically into something resembling the document structure? It seems like this would be in line with the goal of making editing as painless as possible. :-)

**Comment by matt-maguire** [comment]
The directory structure does have implications for the section numbering structure, so the directories structure is already aligned to document TOC structure. Within a section, the order of subsections is determined by the "weight" attribute in the YAML header.

**Comment by junkyardsparkle** [comment]
So.then, are the names determined in such a way that this "weight" value couldn't be prepended to file names? I guess that's what I'm looking for.

**Comment by matt-maguire** [comment]
I guess it is possible, but those weights would be exposed in the URLs. I'll leave for Chris comment on how he wants to handle this.

**Comment by elstoc** [comment]
It would have other implications on the overall structure of the pages. For example, as @matt-maguire says, the file and directory names are used in links and are used to generate URLs. We also have a convention to only have subdirectories for sections that have sub-sections and we'd have to mess with this as well. Take the lighttable section, for example:

![Screenshot_2020-10-16_23-42-21](https://user-images.githubusercontent.com/9555491/96320103-4dbe4f80-1009-11eb-89dd-eb2e12fe6b1c.png)

The weight to determine the first level section structure is applied to the metadata of the following files

```
digital-asset-management/_index.md
lighttable-modes/_index.md
lighttable-view-layout.md
overview.md
undo-redo.md
```

To name as you suggest would essentially need the latter three files to all be moved to subdirectories and for us to prefix those subdirectories with a number. Because of how hugo works they would also all have to be renamed to `_index.md`. Currently all files named `_index.md` are just placeholders for section headers and don't contain any content. What you suggest would mean that we'd have loads of content files all called `_index.md`, which is not ideal.

There are a few things like this where hugo forces us down a particular path. I'm not saying what we've settled on is necessarily the best solution but given the compromises, I think it's probably the least bad.

Worth noting as well that the current user manual is similarly structured.

**Comment by junkyardsparkle** [comment]
> There are a few things like this where hugo forces us down a particular path

I guessed that was probably the case, thanks for the comprehensive explanation.

> Worth noting as well that the current user manual is similarly structured.

Well, in the case of my edits to the "color spaces" docbook source, it was all a single file... whereas here it's split into seven.... but in any case, not a big deal. Just thought I'd ask.

**Comment by elstoc** [comment]
Definitely worth questioning this sort of thing. I went through much the same thought process early on in the dev so can't hurt to have the discussion.
