### ISSUE TITLE
Document module grouping feature

### ISSUE THREAD

**Issue by matt-maguire** [elstoc/dtdocs#87]
@AlicVB has proposed an update the the usermanual concerning the new module grouping feature in PR darktable-org/darktable#6576

This needs to be proof-read and converted to markdown.

**Comment by elstoc** [comment]
Much of that PR in the official manual is fixes because the current manual groups all of the module reference sections together. #6576 is already documented in `module-reference/utility-modules/darkroom/manage-module-layouts.md`.

This just needs a new screenshot and a correct description of the default presets delivered in #6489

**Comment by AlicVB** [comment]
That's great !... but now I'm a bit lost...

At some point (preferably sooner than later) we should define clearly what will be the base for 3.4 documentation. Your work or the legacy one ? No strong opinion here (I don't mind writing in one or another format, the main difficulty for me is English)
Because at some point we will diverge too much I fear...

Example : 
- there's some small points I'd like to add/change in @elstoc version of modulegroups manager
- there's certainly lot to fix and change in my PR based on the legacy workflow

Should we maintain and update both version in parallel for 3.4 ? Again, not a real problem for me (@elstoc as done all the work for its part), but we should just decide and propose clear timeline imho

**Comment by elstoc** [comment]
> At some point (preferably sooner than later) we should define clearly what will be the base for 3.4 documentation.

I agree, but it's hard to commit to this one being the official one right now because bits of it are still WIP. Certainly translation is the big unknown at the moment - though we could certainly manage to release it in English by Christmas. I'd assumed that the current manual would remain the official one for the release. We'd have to fix the help links within darktable itself to point to the new manual, but perhaps we could include those as part of a subsequent patch. I don't have strong opinions either way.

> there's some small points I'd like to add/change in @elstoc version of modulegroups manager

Feel free to raise an issue or propose a PR - your review would be greatly appreciated

> there's certainly lot to fix and change in my PR based on the legacy workflow

We saw that one coming and is one of the reasons we've removed the grouping from the module reference section.

> Should we maintain and update both version in parallel for 3.4 ?

I think that might be best for now, though it's horrible that you have to do all that reordering in the official version.
